# Generated by Django 4.1.7 on 2023-04-27 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_num', models.CharField(max_length=2, verbose_name='Группа')),
                ('description', models.CharField(max_length=50, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ФИО')),
                ('age', models.IntegerField(max_length=3, verbose_name='Возраст')),
                ('sex', models.IntegerField(choices=[(1, 'Ж'), (2, 'М')], max_length=1, verbose_name='Sex')),
                ('in_group', models.ForeignKey(default='0', max_length=10, on_delete=django.db.models.deletion.CASCADE, to='students.group')),
            ],
        ),
    ]
