# Generated by Django 4.1.7 on 2023-04-13 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.TextField(verbose_name='Производитель')),
                ('years_of_production', models.TextField(verbose_name='Годы производства')),
                ('body_type', models.TextField(verbose_name='Тип кузова')),
                ('platform', models.TextField(verbose_name='Платформа')),
                ('layout', models.TextField(verbose_name='Компоновка')),
                ('description', models.TextField(verbose_name='Описание')),
                ('link', models.URLField(verbose_name='Ссылка на википедию')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
            ],
        ),
    ]
