# Generated by Django 4.1.7 on 2023-03-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=1)),
                ('group_id', models.CharField(max_length=5)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
    ]
