# Generated by Django 4.1.7 on 2023-03-31 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('how', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='students',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='students',
            name='group_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='students',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='students',
            name='sex',
            field=models.TextField(),
        ),
    ]
