# Generated by Django 4.1.7 on 2023-04-21 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GropNum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grop_num', models.CharField(max_length=2, verbose_name='Группа')),
                ('description', models.CharField(max_length=50, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ФИО')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('sex', models.IntegerField(choices=[(1, 'Ж'), (2, 'М')], verbose_name='Sex')),
                ('in_grop', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='rest.gropnum')),
            ],
        ),
    ]
